package com.ziran.meiliao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ziran.meiliao.ui.bean.AuthorBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTHOR_BEAN".
*/
public class AuthorBeanDao extends AbstractDao<AuthorBean, Long> {

    public static final String TABLENAME = "AUTHOR_BEAN";

    /**
     * Properties of entity AuthorBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Descript = new Property(2, String.class, "descript", false, "DESCRIPT");
        public final static Property HeadImg = new Property(3, String.class, "headImg", false, "HEAD_IMG");
        public final static Property TeaIntro = new Property(4, String.class, "teaIntro", false, "TEA_INTRO");
    }


    public AuthorBeanDao(DaoConfig config) {
        super(config);
    }
    
    public AuthorBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTHOR_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"DESCRIPT\" TEXT," + // 2: descript
                "\"HEAD_IMG\" TEXT," + // 3: headImg
                "\"TEA_INTRO\" TEXT);"); // 4: teaIntro
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTHOR_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AuthorBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String descript = entity.getDescript();
        if (descript != null) {
            stmt.bindString(3, descript);
        }
 
        String headImg = entity.getHeadImg();
        if (headImg != null) {
            stmt.bindString(4, headImg);
        }
 
        String teaIntro = entity.getTeaIntro();
        if (teaIntro != null) {
            stmt.bindString(5, teaIntro);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AuthorBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String descript = entity.getDescript();
        if (descript != null) {
            stmt.bindString(3, descript);
        }
 
        String headImg = entity.getHeadImg();
        if (headImg != null) {
            stmt.bindString(4, headImg);
        }
 
        String teaIntro = entity.getTeaIntro();
        if (teaIntro != null) {
            stmt.bindString(5, teaIntro);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AuthorBean readEntity(Cursor cursor, int offset) {
        AuthorBean entity = new AuthorBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // descript
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // headImg
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // teaIntro
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AuthorBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescript(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHeadImg(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTeaIntro(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AuthorBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AuthorBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AuthorBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
