package com.ziran.meiliao.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 7): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 7;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        AlbumEntryDao.createTable(db, ifNotExists);
        CachePageEntryDao.createTable(db, ifNotExists);
        CourseEntryDao.createTable(db, ifNotExists);
        DownloadDataDao.createTable(db, ifNotExists);
        ExercisePageEntryDao.createTable(db, ifNotExists);
        ExerciseProgressEntryDao.createTable(db, ifNotExists);
        FolderEntryDao.createTable(db, ifNotExists);
        GainSpreadDayEmtryDao.createTable(db, ifNotExists);
        MusicEntryDao.createTable(db, ifNotExists);
        SearchEntryDao.createTable(db, ifNotExists);
        UserInfoDao.createTable(db, ifNotExists);
        VideoSectionEntryDao.createTable(db, ifNotExists);
        AuthorBeanDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        AlbumEntryDao.dropTable(db, ifExists);
        CachePageEntryDao.dropTable(db, ifExists);
        CourseEntryDao.dropTable(db, ifExists);
        DownloadDataDao.dropTable(db, ifExists);
        ExercisePageEntryDao.dropTable(db, ifExists);
        ExerciseProgressEntryDao.dropTable(db, ifExists);
        FolderEntryDao.dropTable(db, ifExists);
        GainSpreadDayEmtryDao.dropTable(db, ifExists);
        MusicEntryDao.dropTable(db, ifExists);
        SearchEntryDao.dropTable(db, ifExists);
        UserInfoDao.dropTable(db, ifExists);
        VideoSectionEntryDao.dropTable(db, ifExists);
        AuthorBeanDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AlbumEntryDao.class);
        registerDaoClass(CachePageEntryDao.class);
        registerDaoClass(CourseEntryDao.class);
        registerDaoClass(DownloadDataDao.class);
        registerDaoClass(ExercisePageEntryDao.class);
        registerDaoClass(ExerciseProgressEntryDao.class);
        registerDaoClass(FolderEntryDao.class);
        registerDaoClass(GainSpreadDayEmtryDao.class);
        registerDaoClass(MusicEntryDao.class);
        registerDaoClass(SearchEntryDao.class);
        registerDaoClass(UserInfoDao.class);
        registerDaoClass(VideoSectionEntryDao.class);
        registerDaoClass(AuthorBeanDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
