package com.ziran.meiliao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ziran.meiliao.entry.GainSpreadDayEmtry;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GAIN_SPREAD_DAY_EMTRY".
*/
public class GainSpreadDayEmtryDao extends AbstractDao<GainSpreadDayEmtry, Long> {

    public static final String TABLENAME = "GAIN_SPREAD_DAY_EMTRY";

    /**
     * Properties of entity GainSpreadDayEmtry.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DayTime = new Property(1, String.class, "dayTime", false, "DAY_TIME");
        public final static Property IsShow = new Property(2, boolean.class, "isShow", false, "IS_SHOW");
    }


    public GainSpreadDayEmtryDao(DaoConfig config) {
        super(config);
    }
    
    public GainSpreadDayEmtryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GAIN_SPREAD_DAY_EMTRY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DAY_TIME\" TEXT," + // 1: dayTime
                "\"IS_SHOW\" INTEGER NOT NULL );"); // 2: isShow
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GAIN_SPREAD_DAY_EMTRY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GainSpreadDayEmtry entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String dayTime = entity.getDayTime();
        if (dayTime != null) {
            stmt.bindString(2, dayTime);
        }
        stmt.bindLong(3, entity.getIsShow() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GainSpreadDayEmtry entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String dayTime = entity.getDayTime();
        if (dayTime != null) {
            stmt.bindString(2, dayTime);
        }
        stmt.bindLong(3, entity.getIsShow() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GainSpreadDayEmtry readEntity(Cursor cursor, int offset) {
        GainSpreadDayEmtry entity = new GainSpreadDayEmtry( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // dayTime
            cursor.getShort(offset + 2) != 0 // isShow
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GainSpreadDayEmtry entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDayTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsShow(cursor.getShort(offset + 2) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GainSpreadDayEmtry entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GainSpreadDayEmtry entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GainSpreadDayEmtry entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
